theme: jekyll-theme-cayman
title: Kathryn Monopoli
description: I am a Bioinformatics Ph.D. candidate at UMass Medical School and Worcester Polytechnic Institute. 

description: I transitioned from the bench where I studied membrane protein biophysics, to computational research where I apply machine learning technques to studying small interfering RNAs (siRNAs).
