theme: jekyll-theme-cayman
title: Kathryn Monopoli
description: I am a Ph.D. candidate studying Bioinformatics. I transitioned from the bench where I studied membrane protein biophysics to computational research studying small interfering RNAs (siRNAs).
