theme: jekyll-theme-cayman
title: Kathryn Monopoli
description: I am a Bioinformatics Ph.D. candidate at UMass Medical School and Worcester Polytechnic Institute. I transitioned from the bench where I studied membrane protein biophysics, to computational research where I am applying machine learning techniques to study small interfering RNAs (siRNAs).
